name: Build and Push Webex Distrobox Image

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y podman curl git
          curl -s https://raw.githubusercontent.com/89luca89/distrobox/main/install | sudo sh

      - name: Create distrobox from webex.ini
        run: |
          distrobox assemble create --file webex.ini
          # Make sure container exists
          podman ps -a

      - name: Clone distrobox container into an image
        run: |
          IMAGE_NAME=ghcr.io/${{ github.repository }}/webex-distrobox:latest
          distrobox-export --clone Webex-Distrobox --image $IMAGE_NAME
          podman images

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push cloned image
        run: |
          IMAGE_NAME=ghcr.io/${{ github.repository }}/webex-distrobox:latest
          podman push $IMAGE_NAME
